#ifndef COUNT_CONFIG_H
#define COUNT_CONFIG_H 1

/*
** This file is automatically generated by the Count-config script 
** Count-config
** Counter Version: 2.5 by ma_muquit@fccc.edu
** created on: Sun Jan  3 18:08:16 EST 1999
**
**  If you edit this file, you better make sure you know what your are doing 
*/
#define CONFIG_DIR  "/usr/local/etc/Counter/conf"
#define CONFIG_FILE "count.cfg"
#define DATA_DIR    "/usr/local/etc/Counter/data"
#define DIGIT_DIR   "/usr/local/etc/Counter/digits"
#define LOG_DIR     "/usr/local/etc/Counter/logs"
#define LOG_FILE    "Count2_5.log"

/*****************************************************************************
* Defaults parameters not supplied in calling.
* Change em here if you insist...
*****************************************************************************/
/*
** Max digitis in output 
*/
#define DEFAULT_MAXDIGITS           6

/*
** left padding with zeros, 0 indicates no left padding
*/
#define DEFAULT_LEFTPAD             True

/*
** Default frame thickness, 0 indicates no frame
*/
#define DEFAULT_FRAME_THICKNESS     0

/*
** default frame color is #a7c2ed
*/
#define DEFAULT_FRAME_RED           100
#define DEFAULT_FRAME_GREEN         139
#define DEFAULT_FRAME_BLUE          216

/*
** default opaque color. Do not change this.
*/
#define DEFAULT_OPAQUE_RED          0
#define DEFAULT_OPAQUE_GREEN        255
#define DEFAULT_OPAQUE_BLUE         0

/*
** default pen color
*/
#define DEFAULT_PEN_RED             255
#define DEFAULT_PEN_GREEN           119
#define DEFAULT_PEN_BLUE            0
/*
** use this ft if we get frgb only
*/
#define FRGB_IMPLIED_FT             4

/*
** default transpareny
*/
#define DEFAULT_TRANSPARENCY        False

/*
** default transparent color is black
*/
#define DEFAULT_TRANSPARENT_RED     0
#define DEFAULT_TRANSPARENT_GREEN   0
#define DEFAULT_TRANSPARENT_BLUE    0

/*
** use this tr, if we get trgb only
*/
#define TRGB_IMPLIED_TR             1

/*
** default initial counter value
*/
#define DEFAULT_STARTCOUNT          1

/*
** show count or not
*/
#define DEFAULT_SHOWCOUNT           1

/*
** this df means, use rand 
*/
#define DF_FOR_RANDOM               "RANDOM"

/*
** make rand the default too
*/
#define DEFAULT_DATAFILE            "RANDOM"

/*
** default digit style, my green LED, digits/A
*/
#define DEFAULT_DIGITS_STYLE        "A"

/*
** & or | separate params
*/
#define PARAM_DELIMITERS            "|&"

/*
** This specifies a file listing RGB values mapped to names.
** If not defined, no attempt to use RGB names is made.  If you are not sure,   
** just leave this be--it is okay if the file does not exist.
**
** When RGB_MAPPING_ISERROR is set to 1, an error is returned when RGB name
** value is used, but it shows the corresponding RGB triplet.  This is done
** so RGB names can be looked up, but yet not allow users to make constant
** use of this very ineffiecient lookup.
*/
#define RGB_MAPPING_DICT            "/usr/local/etc/Counter/rgb.txt"
/*
** End of parameter defaults
*/
#endif /* COUNT_CONFIG_H*/
